
  CREATE TABLE "SYSTEM"."TWEET" 
   (	"DATAZIONE" TIMESTAMP (6), 
	"ID_TWEET" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"TEXT" VARCHAR2(180 BYTE), 
	"IN_REPLY_TO_STATUS_ID_STR" VARCHAR2(20 BYTE), 
	"IN_REPLY_TO_USER_ID_STR" VARCHAR2(15 BYTE), 
	"IN_REPLY_TO_SCREEN_NAME" VARCHAR2(20 BYTE), 
	"ID_UTENTE" VARCHAR2(20 BYTE), 
	"FOLLOWERS_COUNT" NUMBER(*,0), 
	"FRIENDS_COUNT" NUMBER(*,0), 
	"FAVOURITES_COUNT" NUMBER(*,0), 
	"STATUSES_COUNT" NUMBER(*,0), 
	"ID_RETWEET" VARCHAR2(50 BYTE), 
	"HASHTAG1" VARCHAR2(180 BYTE), 
	"HASHTAG2" VARCHAR2(180 BYTE), 
	"HASHTAG3" VARCHAR2(180 BYTE), 
	"HASHTAG4" VARCHAR2(180 BYTE), 
	"HASHTAG5" VARCHAR2(180 BYTE), 
	"HASHTAG6" VARCHAR2(180 BYTE), 
	"URLS" NUMBER(*,0), 
	"LANGS" VARCHAR2(10 BYTE), 
	"PAROLA_CHIAVE" VARCHAR2(100 BYTE), 
	 CONSTRAINT "TWITTER_TWEET_PK" PRIMARY KEY ("ID_TWEET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_STATUS_ID" FOREIGN KEY ("IN_REPLY_TO_STATUS_ID_STR")
	  REFERENCES "SYSTEM"."TWEET" ("ID_TWEET") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_ID_RETWEET" FOREIGN KEY ("ID_RETWEET")
	  REFERENCES "SYSTEM"."TWEET" ("ID_TWEET") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_SCREEN_NAME" FOREIGN KEY ("IN_REPLY_TO_SCREEN_NAME")
	  REFERENCES "SYSTEM"."UTENTE" ("SCREEN_NAME") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_USER_ID" FOREIGN KEY ("IN_REPLY_TO_USER_ID_STR")
	  REFERENCES "SYSTEM"."UTENTE" ("ID_UTENTE") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
